INFO 2020-11-11 10:11:06,004 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:11:14,283 [basehttp.py:157] [basehttp:log_message] - "POST /user/register/ HTTP/1.1" 200 7
INFO 2020-11-11 10:13:40,776 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\views.py changed, reloading.
INFO 2020-11-11 10:13:41,382 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:13:52,806 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\views.py changed, reloading.
INFO 2020-11-11 10:13:53,377 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:13:56,750 [basehttp.py:157] [basehttp:log_message] - "GET /user/register/ HTTP/1.1" 200 927
ERROR 2020-11-11 10:14:01,418 [views.py:27] [views:register] - 数据库操作失败
ERROR 2020-11-11 10:14:01,450 [log.py:224] [log:log_response] - Internal Server Error: /user/register/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "D:\python\sunday\user\views.py", line 29, in register
    raise e
  File "D:\python\sunday\user\views.py", line 25, in register
    UserInfo.objects.create(**form.cleaned_data)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\query.py", line 445, in create
    obj = self.model(**kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\base.py", line 501, in __init__
    raise TypeError("%s() got an unexpected keyword argument '%s'" % (cls.__name__, kwarg))
TypeError: UserInfo() got an unexpected keyword argument 'repeat_pwd'
ERROR 2020-11-11 10:14:01,451 [basehttp.py:157] [basehttp:log_message] - "POST /user/register/ HTTP/1.1" 500 91470
INFO 2020-11-11 10:15:21,670 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\views.py changed, reloading.
INFO 2020-11-11 10:15:22,244 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:15:26,514 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\views.py changed, reloading.
INFO 2020-11-11 10:15:27,099 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:15:36,348 [basehttp.py:157] [basehttp:log_message] - "POST /user/register/ HTTP/1.1" 200 7
INFO 2020-11-11 10:17:07,455 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\views.py changed, reloading.
INFO 2020-11-11 10:17:08,037 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:17:43,956 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\views.py changed, reloading.
INFO 2020-11-11 10:17:44,525 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:18:21,633 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\views.py changed, reloading.
INFO 2020-11-11 10:18:22,207 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:23:52,526 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\sunday\settings.py changed, reloading.
INFO 2020-11-11 10:23:53,116 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:26:20,544 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\apps.py changed, reloading.
INFO 2020-11-11 10:26:21,121 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:27:38,968 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\sunday\urls.py changed, reloading.
INFO 2020-11-11 10:27:39,559 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:27:46,875 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\index\urls.py changed, reloading.
INFO 2020-11-11 10:27:47,459 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:28:10,099 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\sunday\settings.py changed, reloading.
INFO 2020-11-11 10:28:10,683 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:28:17,349 [basehttp.py:157] [basehttp:log_message] - "GET /index/ HTTP/1.1" 200 5
INFO 2020-11-11 10:34:15,724 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\views.py changed, reloading.
INFO 2020-11-11 10:34:16,357 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:34:38,976 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\urls.py changed, reloading.
INFO 2020-11-11 10:34:39,558 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:35:17,505 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\urls.py changed, reloading.
INFO 2020-11-11 10:35:18,158 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:40:07,822 [basehttp.py:157] [basehttp:log_message] - "GET /user/login HTTP/1.1" 301 0
INFO 2020-11-11 10:40:07,835 [basehttp.py:157] [basehttp:log_message] - "GET /user/login/ HTTP/1.1" 200 276
WARNING 2020-11-11 10:40:14,018 [log.py:224] [log:log_response] - Forbidden (CSRF token missing or incorrect.): /user/login/
WARNING 2020-11-11 10:40:14,018 [basehttp.py:157] [basehttp:log_message] - "POST /user/login/ HTTP/1.1" 403 2513
INFO 2020-11-11 10:42:22,480 [basehttp.py:157] [basehttp:log_message] - "GET /user/login/ HTTP/1.1" 200 330
INFO 2020-11-11 10:42:30,467 [basehttp.py:157] [basehttp:log_message] - "GET /user/register/ HTTP/1.1" 200 927
INFO 2020-11-11 10:43:46,808 [basehttp.py:157] [basehttp:log_message] - "GET /user/login/ HTTP/1.1" 200 402
ERROR 2020-11-11 10:43:51,965 [log.py:224] [log:log_response] - Internal Server Error: /user/login/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\user\views.py", line 38, in login
    res = UserInfo.objects.get(request.POST)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\sql\query.py", line 1235, in build_filter
    raise FieldError("Cannot parse keyword query as dict")
django.core.exceptions.FieldError: Cannot parse keyword query as dict
ERROR 2020-11-11 10:43:51,966 [basehttp.py:157] [basehttp:log_message] - "POST /user/login/ HTTP/1.1" 500 105680
INFO 2020-11-11 10:45:21,899 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\views.py changed, reloading.
INFO 2020-11-11 10:45:22,516 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:48:43,267 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\views.py changed, reloading.
INFO 2020-11-11 10:48:43,870 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
ERROR 2020-11-11 10:48:53,566 [log.py:224] [log:log_response] - Internal Server Error: /user/login/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\user\views.py", line 39, in login
    res = UserInfo.objects.get(username='111')
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\db\models\query.py", line 429, in get
    raise self.model.DoesNotExist(
user.models.UserInfo.DoesNotExist: UserInfo matching query does not exist.
ERROR 2020-11-11 10:48:53,567 [basehttp.py:157] [basehttp:log_message] - "POST /user/login/ HTTP/1.1" 500 76212
INFO 2020-11-11 10:55:53,202 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\views.py changed, reloading.
INFO 2020-11-11 10:55:53,810 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 10:56:00,146 [basehttp.py:157] [basehttp:log_message] - "POST /user/login/ HTTP/1.1" 200 4
INFO 2020-11-11 10:59:42,934 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\views.py changed, reloading.
INFO 2020-11-11 10:59:43,567 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 11:00:30,729 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\views.py changed, reloading.
