INFO 2020-11-11 18:01:55,858 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 18:02:02,229 [basehttp.py:157] [basehttp:log_message] - "GET /admin/ HTTP/1.1" 200 5216
INFO 2020-11-11 18:02:04,260 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/ HTTP/1.1" 200 8668
INFO 2020-11-11 18:02:04,280 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 18:02:19,901 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/add/ HTTP/1.1" 200 9189
INFO 2020-11-11 18:02:19,927 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 18:02:56,843 [basehttp.py:157] [basehttp:log_message] - "POST /admin/user/userinfo/add/ HTTP/1.1" 302 0
ERROR 2020-11-11 18:02:56,887 [log.py:224] [log:log_response] - Internal Server Error: /admin/user/userinfo/5/change/
Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 709, in get_form
    return modelform_factory(self.model, **defaults)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 555, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "D:\python\sunday\venv\lib\site-packages\django\forms\models.py", line 268, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (first_name, last_name) specified for UserInfo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\python\sunday\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 1568, in _changeform_view
    ModelForm = self.get_form(
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\auth\admin.py", line 80, in get_form
    return super().get_form(request, obj, **defaults)
  File "D:\python\sunday\venv\lib\site-packages\django\contrib\admin\options.py", line 711, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (first_name, last_name) specified for UserInfo. Check fields/fieldsets/exclude attributes of class UserProfileAdmin.
ERROR 2020-11-11 18:02:56,889 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/5/change/ HTTP/1.1" 500 143004
INFO 2020-11-11 18:05:00,818 [autoreload.py:236] [autoreload:trigger_reload] - D:\python\sunday\user\models.py changed, reloading.
INFO 2020-11-11 18:05:01,413 [autoreload.py:613] [autoreload:run_with_reloader] - Watching for file changes with StatReloader
INFO 2020-11-11 18:05:12,787 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/add/ HTTP/1.1" 200 9424
INFO 2020-11-11 18:05:31,294 [basehttp.py:157] [basehttp:log_message] - "POST /admin/user/userinfo/add/ HTTP/1.1" 200 9423
INFO 2020-11-11 18:05:31,315 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 18:05:43,000 [basehttp.py:157] [basehttp:log_message] - "POST /admin/user/userinfo/add/ HTTP/1.1" 200 9486
INFO 2020-11-11 18:05:43,020 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 18:05:54,238 [basehttp.py:157] [basehttp:log_message] - "POST /admin/user/userinfo/add/ HTTP/1.1" 200 9417
INFO 2020-11-11 18:05:54,268 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 18:06:09,932 [basehttp.py:157] [basehttp:log_message] - "POST /admin/user/userinfo/add/ HTTP/1.1" 302 0
INFO 2020-11-11 18:06:10,010 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/6/change/ HTTP/1.1" 200 15421
INFO 2020-11-11 18:06:10,046 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 18:06:43,671 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/6/password/ HTTP/1.1" 200 4787
INFO 2020-11-11 18:06:43,695 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
INFO 2020-11-11 18:06:51,852 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/6/change/ HTTP/1.1" 200 15184
INFO 2020-11-11 18:07:24,700 [basehttp.py:157] [basehttp:log_message] - "POST /admin/user/userinfo/6/change/ HTTP/1.1" 302 0
INFO 2020-11-11 18:07:24,756 [basehttp.py:157] [basehttp:log_message] - "GET /admin/user/userinfo/ HTTP/1.1" 200 9518
INFO 2020-11-11 18:07:24,779 [basehttp.py:157] [basehttp:log_message] - "GET /admin/jsi18n/ HTTP/1.1" 200 7732
